MAX_ALPHA = 255

GRAVITY_LEFT = 0
GRAVITY_RIGHT = 1
GRAVITY_TOP = 0
GRAVITY_BOTTOM = 2
GRAVITY_CENTER_HORIZONTAL = 4
GRAVITY_CENTER_VERTICAL = 8

STYLE_NORMAL = 0
STYLE_BOLD = 1
STYLE_ITALIC = 2

MOUSE_MODE_CONFINED = 1
MOUSE_MODE_CAPTURED = 2
