MAX_ALPHA = 255
MAX_SCALE = 1.0

GRAVITY_RIGHT = 1
GRAVITY_BOTTOM = 2
GRAVITY_CENTER_HORIZONTAL = 4
GRAVITY_CENTER_VERTICAL = 8

STYLE_NORMAL = 0
STYLE_BOLD = 1
STYLE_ITALIC = 2

BAR_STEP = 0
BAR_MIN_VALUE = 1
BAR_MAX_VALUE = 2
BAR_VALUE = 3
